version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/lib/python3.9/site-packages"
      - run:
          name: Check style of Python Scripts with black
          command: |
            black --check otmarkov
      - run:
          name: Check style of Python Scripts with flake8
          command: |
            flake8 otmarkov
      - run:
          name: Check style of Notebooks with black-nb
          command: |
            black-nb --check .
      - run:
          name: Test
          command: ./.circleci/run_docker_linux.sh
workflows:
  main:
    jobs:
      - build-and-test

